---
- hosts: all
  gather_facts: no
  user: adminroot
  become: yes
  tasks: 
    - name: Run make upgrade to check node status
      command: make upgrade
      args:
        chdir: /root/chainpoint-node
      register: shell_result

    - debug:
        var: shell_result.stdout_lines
